# Generated by Django 6.0 on 2025-12-31 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
