# Generated by Django 6.0 on 2026-01-01 19:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_alter_post_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
